version: '3.8'
services:
  postgres-db:
    image: postgres:15-alpine
    restart: unless-stopped
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes:
      - postgres-db:/var/lib/postgresql/data
  graphql-api:
    image: node:18-alpine
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres-db
    environment:
      - DATABASE_HOST=postgres-db
      - DATABASE_PORT=5432
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=postgres
    ports:
      - '4000:4000'
    volumes:
      - ./:/app
volumes:
  postgres-db:
    driver: local
